Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.provider "libvirt" do |hv|
    hv.cpus = "1"
    hv.memory = "1024"
  end
  config.vm.define "client2" do |client2|
   client2.vm.network :private_network, ip: "10.10.20.5"
   client2.vm.hostname = "client2"
  end
end
