Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.provider "libvirt" do |hv|
    hv.cpus = "2"
    hv.memory = "2048"
  end
  config.vm.define "ansible" do |ansible|
   ansible.vm.network :private_network, ip: "10.10.20.3"
   ansible.vm.hostname = "ansible"
  end
end
