Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.provider "libvirt" do |hv|
    hv.cpus = "1"
    hv.memory = "1024"
  end
  config.vm.define "client1" do |client1|
   client1.vm.network :private_network, ip: "10.10.20.4"
   client1.vm.hostname = "client1"
  end
end
